### ISSUE TITLE
Issue with H264 incompatible camera

### ISSUE THREAD

**Issue by regzon** [Ullaakut/RTSPAllTheThings#72]
I have a web camera that doesn't support H264 format. And the application silently fails on all requests to the RTSP server.

Fix for this problem is a custom GStreamer Pipeline:
```
v4l2src device=/dev/video0 ! capsfilter caps=video/x-raw,width=640,height=480 ! jpegenc ! rtpjpegpay name=pay0 pt=96
```

But I think this could be an option for the application (or maybe there can be automatic detection of supported camera outputs)

**Comment by Ullaakut** [comment]
Hi @Regzon!

Nice suggestion :) This could be a nice feature indeed, but I'm not really able to 100% maintain this project anymore unfortunately, since I have a lot of other stuff on my plate.

If you want, we can either:

- Since I am limited by time, I can add a tip in the README saying that cameras not supporting H264 are not supported by the default pipelines, and recommending to use the pipeline you mentioned
- Or, if you have the time to make a pull request proposing the feature you suggested, I can review it and merge it this week :)

Let me know what works best for you

**Comment by Ullaakut** [comment]
Any update on this @Regzon? Thanks

**Comment by Regzon** [comment]
Sorry for a late reply. I am not working with this camera anymore, so can't test this. I think we can put the hint somewhere in README. That should be okay.
