### ISSUE TITLE
When reading from a large file ( > 300MB ). The rtspatt will tack up all the memory (4GB)

### ISSUE THREAD

**Issue by ingjieye** [Ullaakut/RTSPAllTheThings#76]
Probably it's because rtspatt decode entire file to memory before do anything? It there a way to workaround this?

**Comment by Ullaakut** [comment]
Hi @ingjieye, I guess the only solution is either to allocate more memory or reduce the size of the file by compressing it (you can achieve this easily using [ffmpeg](https://ffmpeg.org/)).

Unfortunately, I'm afraid there's nothing else that can be done to fix this issue, since that's how gstreamer works, which is what is under the hood of RTSPATT :/
